t/common report-and-exit: add a check that at least one assertion has run
Fail the test if no assertions ran, as a safety check.

diff --git a/t/common.sh.in b/t/common.sh.in
--- a/t/common.sh.in
+++ b/t/common.sh.in
@@ -21,9 +21,11 @@ here="$(cd "$(dirname "$0")" ; pwd)"
 
 # Other vars
 export unbuffer_pgm="@UNBUFFER@"
+assertions_run=0
 
 # Find out if a PID represents a running process
 process-exists() {
+    (( ++assertions_run ))
     if [[ "$1" ]]; then
         kill -n 0 "$@" &>/dev/null
     else
@@ -35,6 +37,7 @@ process-exists() {
 # line in the input matches the pattern; fails otherwise.  Usage:
 #   cat foo | has-line-matching '/quux\e/'
 has-line-matching() {
+    (( ++assertions_run ))
     local -r pat="$1"
     shift
     perl -Mstrict -Mwarnings -Mvars='$exitcode' -ne '
@@ -51,17 +54,15 @@ kill-if-exists() {
     fi
 }
 
-# print a message and exit with a given exit code.  Usage:
-# report-and-exit "$exitcode"
+# print a message and exit with an appropriate exit code.  No parameters.
 report-and-exit() {
-    local -r exitcode="$1"
-    if (( ${V:-0} > 0 && exitcode )); then
-        echo "At least one test failed"
+    if (( assertions_run == 0 )); then
+        echo "No tests ran!"
+        exit 1
     else
         echo "All tests passed"
+        exit 0
     fi
-
-    exit "$exitcode"
 }
 
 # Check whether a file (default stdin) does NOT match a particular Perl regex.
@@ -70,6 +71,7 @@ report-and-exit() {
 # or
 #   does-not-contain RE INPUT-FILE
 does-not-contain() {
+    (( ++assertions_run ))
     local -r regex="$1"
     shift
     perl -Mstrict -Mwarnings -ne 'm{'"$regex"'} and exit(1); END { exit(0) }' "$@"
